name: build and push sub directory
inputs:
  folder:
    required: true
runs:
  using: "composite"
  steps:
    -
      name: build
      run: |
        ${{ inputs.folder }}/build.bash
        export TAGNAME=$(<${{ inputs.folder }}/.tag)
        docker push $TAGNAME

